services:
  backend:
    build: backend
    container_name: api
    ports:
      - 8008:80
    environment:
      - DATABASE_URL=asyncpg://fastapi:fastapi@db:5432/schedule
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8080 --loop uvloop
    networks:
      - app_network
    depends_on:
      - db

  frontend:
    build: frontend_v2
    container_name: front
    ports:
      - 8009:80
    environment:
      - API_URL=http://api:8000
    command: uvicorn frontend.main:app --host 0.0.0.0 --port 8080
    networks:
      - app_network

#  prepare:
#    build: dataloader
#    command: python dataloader.py
#    environment:
#      - URL=http://api:8080
#    depends_on:
#      - backend
#    networks:
#      - app_network

  prometheus:
    container_name: prometheus
    build: prometheus
    networks:
      - app_network
    environment:
      TZ: Europe/Moscow
    ports:
      - 9090:9090

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=schedule
    networks:
      - app_network


networks:
  app_network:


volumes:
  postgres_data:
