services:
  backend:
    build: backend
    container_name: api
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=sqlite://db.sqlite3
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    networks:
      - app_network

  frontend:
    build: frontend
    container_name: front
    ports:
      - 8009:8000

    environment:
      - API_URL=http://api:8000
    command: uvicorn frontend.main:app --host 0.0.0.0 --port 8000
    networks:
      - app_network

  prepare:
    build: dataloader
    command: python dataloader.py
    environment:
      - URL=http://localhost:8008
    depends_on:
      - backend
    network_mode: host

networks:
  app_network:
