services:
  web:
    build: backend
    container_name: api
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=sqlite://db.sqlite3
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000

  prepare:
    build: dataloader
    command: python dataloader.py
    environment:
      - URL=http://localhost:8008
    depends_on:
      - web
    network_mode: host